name: Deploy Plugin to WordPress

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  web-deploy:
    name: Sync to WordPress Server
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 72.62.207.115
          username: u460037536.royalblue-raccoon-912134.hostingersite.com
          password: ${{ secrets.FTP_PASSWORD }}
          timeout: 120000
          server-dir: wp-content/plugins/styler-for-woo/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            README.md
